const router = require('express').Router()
const ctrls = require('../controllers/user')
const uploader = require('../config/cloundinary.config')

const { verifyAccessToken, isAdmin } = require('../middlewares/verifyToken')
router.post('/register', ctrls.register)
router.post('/login', ctrls.login)
router.get('/current', verifyAccessToken, ctrls.getCurrent)
router.post('/refreshtoken', ctrls.refreshAccessToken)
router.get('/logout', ctrls.logout)
router.post('/forgotpassword', ctrls.forgotPassword)
router.put('/resetpassword', ctrls.resetPassword)
router.put('/handlepassword',verifyAccessToken, ctrls.handlePassword)
router.get('/', [verifyAccessToken, isAdmin], ctrls.getUsers)
router.get('/cart', [verifyAccessToken], ctrls.getCart)
router.delete('/cart', [verifyAccessToken], ctrls.deleteCart)
router.delete('/allcart', [verifyAccessToken], ctrls.deleteAllCart)

router.put('/current', [verifyAccessToken], ctrls.updateUser)
router.put('/address', [verifyAccessToken], ctrls.updateUserAddress)
router.put('/cart', [verifyAccessToken], ctrls.updateCart)
router.put('/finalregister/:token', ctrls.finalRegister)
router.delete('/:uid', [verifyAccessToken, isAdmin], ctrls.deleteUser)
router.get('/:uid', [verifyAccessToken, isAdmin], ctrls.getUserByadmin)
router.put('/:uid', [verifyAccessToken], ctrls.updateUserByAdmin)
router.put('/uploadavatar/:uid', [verifyAccessToken], uploader.single('avatar'), ctrls.uploadAvatar)

module.exports = router